### ISSUE TITLE
Example code?

### ISSUE THREAD

**Issue by headsphere** [oreillymedia/doing_data_science#3]
I may be missing something but I cannot see any example code anywhere in this repository. The zip file only contains the datasets. Could someone please point me to where to code is? Thanks

**Comment by kristenORM** [comment]
As you noted, the code in the zip file is just sample data, not the examples from within the book itself. The code from the book isn't currently available for download.

**Comment by headsphere** [comment]
You may want to update the description in the readme then:

"This is the example code than accompanies Doing Data Science by Cathy O'Neil and Rachel Schutt (9781449358655). "

**Comment by kristenORM** [comment]
Done, thank you for the suggestion!
